name: Generate Gradle SBOM per Submodule

on:
  push:
    branches: 
      - "main"
      - "generate-submodule-sbom"
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: 'main'
        required: true

env:
  JAVA_VERSION: '21'
  JAVA_DISTRO: 'temurin'
  arc-spring-boot-starter: '5460d2f8-38c3-478e-9934-46fddb6b7794'
  # arc-streaming-spring-boot-starter: 'f359703e-da69-4e4a-9162-acdd065752ad'
  # arc-view-spring-boot-starter: 'be1b9fea-6c7e-42b3-9f6f-db4102acc085'


permissions:
  contents: read

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    outputs:
      sboms: ${{ steps.get-sboms.outputs.sboms }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.version }}

      - name: Setup Java SDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Generate sbom
        run: |
          gradle cyclonedxBom

      - name: Collect submodule SBOM files
        run: |
          event="${{ github.event_name }}"
          ref="${{ github.ref }}"
          input="${{ github.event.inputs.version }}"

          is_dev=""
          if [[ "$event" == "push" && "$ref" == refs/heads/* ]] || \
            [[ "$event" == "workflow_dispatch" && ! "$input" =~ ^v ]]; then
            is_dev="@dev"
          fi

          mkdir sboms

          find . -type f -name "bom.json" -print | while read file; do
            version="$(jq -r '.metadata.component.version' < $file)"
            version="${version}${is_dev}"

            dir_name=$(echo "$file" | cut -d'/' -f2)
            new_name="${dir_name}_bom_${version}.json"
            
            # Check if dir_name exists in the PROJECTS mapping
            exists=$(printenv "$dir_name" >/dev/null && echo "true" || echo "false")
            if [ "$exists" = "true" ]; then
              echo "Uploading: $dir_name."
              cp "$file" "sboms/$new_name"
            else
              echo "Skipping: $dir_name."
            fi
          done
  
      - name: Get SBOMs names
        id: get-sboms
        run: |
          sboms_list=($(ls -A ./sboms/))
          sboms_json=$(printf '"%s", ' "${sboms_list[@]}" | sed 's/, $//')
          sboms_json="[$sboms_json]"

          echo "sboms=$sboms_json" >> $GITHUB_OUTPUT
          echo "SBOM names to upload: ${sboms_json}"

      - name: Upload sbom
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: sbom
          path: sboms/

  test-matrix:
      needs: ['generate-sbom']
      runs-on: ubuntu-latest
      strategy:
        matrix:
          sbom: ${{ fromJson(needs.generate-sbom.outputs.sboms) }}
      steps:
        - name: Parse parameters from sboms list
          run: |
            sbom_name="${{ matrix.sbom }}"
            echo "SBOM_NAME=$sbom_name" >> $GITHUB_ENV
            echo "SBOM Name: $SBOM_NAME"

            projectName="${sbom_name%%_bom_*}"
            echo "PROJECT_NAME=$projectName" >> $GITHUB_ENV
            echo "Project Name: $PROJECT_NAME"
            
            projectVersion="${sbom_name#*_bom_}"
            projectVersion="${projectVersion%.json}"
            echo "PROJECT_VERSION=$projectVersion" >> $GITHUB_ENV
            echo "Project Version: $PROJECT_VERSION"

            parentProject="$(printenv "$PROJECT_NAME")"
            echo "PARENT_PROJECT=$parentProject" >> $GITHUB_ENV
            echo "Parent ID: $PARENT_PROJECT"

        - name: Print parsed parameters
          run: |
            # Print the parsed project name and version
            echo "Project Name: $PROJECT_NAME"
            echo "Project Version: $PROJECT_VERSION"
            echo "SBOM Name: $SBOM_NAME"
            echo "Parent ID: $PARENT_PROJECT"

        # - name: Upload to DependencyTrack
        #   uses: eclipse-csi/workflows/.github/workflows/store-sbom-data.yml@main
        #   with:
        #     projectName: ${{ env.PROJECT_NAME }}
        #     projectVersion: ${{ env.PROJECT_VERSION }}
        #     bomArtifact: 'sbom'
        #     bomFilename: '${{ env.SBOM_NAME }}'
        #     parentProject: '${{ env.PARENT_PROJECT }}'


  # store-sbom-data: # stores sbom and metadata in a predefined format for otterdog to pick up
  #   needs: ['generate-sbom']
  #   uses: eclipse-csi/workflows/.github/workflows/store-sbom-data.yml@main
  #   with:
  #     projectName: 'arc'
  #     projectVersion: ${{ needs.generate-sbom.outputs.project-version }}
  #     bomArtifact: 'sbom'
  #     bomFilename: 'bom.json'
  #     parentProject: ''