name: Generate Gradle SBOM per Submodule

on:
  push:
    branches: 
      - "main"
      - "generate-submodule-sbom"
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: 'main'
        required: true

env:
  JAVA_VERSION: '21'
  JAVA_DISTRO: 'temurin'
  arc-spring-boot-starter: '5460d2f8-38c3-478e-9934-46fddb6b7794'
  arc-streaming-spring-boot-starter: 'f359703e-da69-4e4a-9162-acdd065752ad'
  arc-view-spring-boot-starter: 'be1b9fea-6c7e-42b3-9f6f-db4102acc085'


permissions:
  contents: read

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    outputs:
      sboms: ${{ steps.get-sboms.outputs.sboms }}
      projectnames: ${{ steps.get-sboms.outputs.projectnames }}
      projectversions: ${{ steps.get-sboms.outputs.projectversions }}
      parents: ${{ steps.get-sboms.outputs.parents }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.version }}

      - name: Setup Java SDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Generate sbom
        run: |
          gradle cyclonedxBom

      - name: Collect submodule SBOM files
        run: |
          event="${{ github.event_name }}"
          ref="${{ github.ref }}"
          input="${{ github.event.inputs.version }}"

          is_dev=""
          if [[ "$event" == "push" && "$ref" == refs/heads/* ]] || \
            [[ "$event" == "workflow_dispatch" && ! "$input" =~ ^v ]]; then
            is_dev="@dev"
          fi

          mkdir sboms

          find . -type f -name "bom.json" -print | while read file; do
            version="$(jq -r '.metadata.component.version' < $file)"
            version="${version}${is_dev}"

            dir_name=$(echo "$file" | cut -d'/' -f2)
            new_name="${dir_name}_bom_${version}.json"
            
            # Check if dir_name exists in the PROJECTS mapping
            exists=$(printenv "$dir_name" >/dev/null && echo "true" || echo "false")
            if [ "$exists" = "true" ]; then
              echo "Uploading: $dir_name."
              cp "$file" "sboms/$new_name"
            else
              echo "Skipping: $dir_name."
            fi
          done
  
      - name: Get SBOMs names
        id: get-sboms
        run: |
          sboms_list=($(ls -A ./sboms/))
          
          sboms=()
          projectnames=()
          projectversions=()
          parents=()

          for sbom in "${sboms_list[@]}"; do
            sboms+=("$sbom")

            # Parse project name and version
            projectName="${sbom%%_bom_*}"
            projectnames+=("$projectName")

            projectVersion="${sbom#*_bom_}"
            projectVersion="${projectVersion%.json}"
            projectversions+=("$projectVersion")

            # Get parent project from env based on project name
            parentProject="$(printenv "$projectName")"
            parents+=("$parentProject")

          done

          # Convert arrays to JSON
          sboms_json=$(printf '"%s", ' "${sboms[@]}" | sed 's/, $//')
          projectnames_json=$(printf '"%s", ' "${projectnames[@]}" | sed 's/, $//')
          projectversions_json=$(printf '"%s", ' "${projectversions[@]}" | sed 's/, $//')
          parents_json=$(printf '"%s", ' "${parents[@]}" | sed 's/, $//')

          sboms_json="[$sboms_json]"
          projectnames_json="[$projectnames_json]"
          projectversions_json="[$projectversions_json]"
          parents_json="[$parents_json]"

          # Print
          echo "sboms=$sboms_json" >> $GITHUB_OUTPUT
          echo "projectnames=$projectnames_json" >> $GITHUB_OUTPUT
          echo "projectversions=$projectversions_json" >> $GITHUB_OUTPUT
          echo "parents=$parents_json" >> $GITHUB_OUTPUT

          echo "SBOMs: $sboms_json"
          echo "Project Names: $projectnames_json"
          echo "Project Versions: $projectversions_json"
          echo "Parents: $parents_json"

      - name: Upload sbom
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: sbom
          path: sboms/

  test-matrix:
    needs: ['generate-sbom']
    strategy:
      matrix:
        sbom: ${{ fromJson(needs.generate-sbom.outputs.sboms) }}
        projectName: ${{ fromJson(needs.generate-sbom.outputs.projectnames) }}
        projectVersion: ${{ fromJson(needs.generate-sbom.outputs.projectversions) }}
        parentProject: ${{ fromJson(needs.generate-sbom.outputs.parents) }}
    uses: eclipse-csi/workflows/.github/workflows/store-sbom-data.yml@main
    with:
      projectName: ${{ matrix.projectName }}
      projectVersion: ${{ matrix.projectVersion }}
      bomArtifact: 'sbom'
      bomFilename: ${{ matrix.sbom }}
      parentProject:  ${{ matrix.parentProject }}
